//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationPortfolio.Domain.DataConnections
{
    using System;
    using System.Collections.Generic;
    
    public partial class access_types
    {
        public access_types()
        {
            this.webservices = new HashSet<webservice>();
        }
    
        public long access_type_id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<webservice> webservices { get; set; }
    }
}
