//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationPortfolio.Domain.DataConnections
{
    using System;
    using System.Collections.Generic;
    
    public partial class address
    {
        public address()
        {
            this.contacts = new HashSet<contact>();
        }
    
        public long address_id { get; set; }
        public string property_name { get; set; }
        public string uprn { get; set; }
        public string paon { get; set; }
        public string descriptor { get; set; }
        public string locality { get; set; }
        public string county { get; set; }
        public string post_code { get; set; }
        public string usrn { get; set; }
        public string authority { get; set; }
    
        public virtual ICollection<contact> contacts { get; set; }
    }
}
