//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationPortfolio.Domain.DataConnections
{
    using System;
    using System.Collections.Generic;
    
    public partial class application
    {
        public System.Guid application_id { get; set; }
        public long service_area_id { get; set; }
        public long business_criticality_id { get; set; }
    
        public virtual business_criticalities business_criticalities { get; set; }
        public virtual service_area service_area { get; set; }
        public virtual baseobject baseobject { get; set; }
    }
}
