//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationPortfolio.Domain.DataConnections
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationServer
    {
        public int ApplicationServerId { get; set; }
        public System.Guid ApplicationId { get; set; }
        public System.Guid ServerId { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual Server Server { get; set; }
    }
}
