//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationPortfolio.Domain.DataConnections
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public Application()
        {
            this.ApplicationDocuments = new HashSet<ApplicationDocument>();
            this.ApplicationServers = new HashSet<ApplicationServer>();
        }
    
        public System.Guid ApplicationId { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> BusinessContact { get; set; }
        public Nullable<System.Guid> IctContact { get; set; }
        public Nullable<int> BusinessCriticalityId { get; set; }
        public Nullable<int> ServiceAreaId { get; set; }
        public string Description { get; set; }
    
        public virtual BusinessCriticality BusinessCriticality { get; set; }
        public virtual Contact Contact { get; set; }
        public virtual Contact Contact1 { get; set; }
        public virtual ServiceArea ServiceArea { get; set; }
        public virtual ICollection<ApplicationDocument> ApplicationDocuments { get; set; }
        public virtual ICollection<ApplicationServer> ApplicationServers { get; set; }
    }
}
