//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationPortfolio.Domain.DataConnections
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AppPortfolioEntities : DbContext
    {
        public AppPortfolioEntities()
            : base("name=AppPortfolioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Application> Applications { get; set; }
        public DbSet<ApplicationContact> ApplicationContacts { get; set; }
        public DbSet<ApplicationDocument> ApplicationDocuments { get; set; }
        public DbSet<ApplicationServer> ApplicationServers { get; set; }
        public DbSet<BusinessCriticality> BusinessCriticalities { get; set; }
        public DbSet<Contact> Contacts { get; set; }
        public DbSet<Document> Documents { get; set; }
        public DbSet<DocumentType> DocumentTypes { get; set; }
        public DbSet<Server> Servers { get; set; }
        public DbSet<ServerContact> ServerContacts { get; set; }
        public DbSet<ServerDocument> ServerDocuments { get; set; }
        public DbSet<ServiceArea> ServiceAreas { get; set; }
        public DbSet<ApplicationServerDependency> ApplicationServerDependencies { get; set; }
    }
}
