//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationPortfolio.Domain.DataConnections
{
    using System;
    using System.Collections.Generic;
    
    public partial class backup_links
    {
        public long backup_link_id { get; set; }
        public System.Guid server_id { get; set; }
        public long backup_type_id { get; set; }
        public long backup_job_id { get; set; }
    
        public virtual backup_jobs backup_jobs { get; set; }
        public virtual backup_types backup_types { get; set; }
        public virtual server server { get; set; }
    }
}
