//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationPortfolio.Domain.DataConnections
{
    using System;
    using System.Collections.Generic;
    
    public partial class backup_jobs
    {
        public backup_jobs()
        {
            this.backup_links = new HashSet<backup_links>();
        }
    
        public long backup_job_id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<backup_links> backup_links { get; set; }
    }
}
