//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationPortfolio.Domain.DataConnections
{
    using System;
    using System.Collections.Generic;
    
    public partial class baseobject
    {
        public baseobject()
        {
            this.change_requests = new HashSet<change_requests>();
            this.documents = new HashSet<document>();
            this.notification_groups_objects = new HashSet<notification_groups_objects>();
            this.notifications = new HashSet<notification>();
        }
    
        public System.Guid object_id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public long object_type_id { get; set; }
        public Nullable<System.Guid> parent_id { get; set; }
    
        public virtual application application { get; set; }
        public virtual ICollection<change_requests> change_requests { get; set; }
        public virtual ICollection<document> documents { get; set; }
        public virtual network_addresses network_addresses { get; set; }
        public virtual network network { get; set; }
        public virtual ICollection<notification_groups_objects> notification_groups_objects { get; set; }
        public virtual ICollection<notification> notifications { get; set; }
        public virtual object_types object_types { get; set; }
        public virtual server server { get; set; }
        public virtual webserver webserver { get; set; }
    }
}
