//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationPortfolio.Domain.DataConnections
{
    using System;
    using System.Collections.Generic;
    
    public partial class building
    {
        public building()
        {
            this.server_locations = new HashSet<server_locations>();
            this.servers = new HashSet<server>();
        }
    
        public long building_id { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string address3 { get; set; }
        public string town { get; set; }
        public string postcode { get; set; }
    
        public virtual ICollection<server_locations> server_locations { get; set; }
        public virtual ICollection<server> servers { get; set; }
    }
}
