//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationPortfolio.Domain.DataConnections
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact_types
    {
        public contact_types()
        {
            this.contact_links = new HashSet<contact_links>();
            this.contacts = new HashSet<contact>();
        }
    
        public long contact_type_id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<contact_links> contact_links { get; set; }
        public virtual ICollection<contact> contacts { get; set; }
    }
}
