//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationPortfolio.Domain.DataConnections
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public Contact()
        {
            this.Applications = new HashSet<Application>();
            this.Applications1 = new HashSet<Application>();
        }
    
        public System.Guid ContactId { get; set; }
        public Nullable<System.Guid> OpenId { get; set; }
    
        public virtual ICollection<Application> Applications { get; set; }
        public virtual ICollection<Application> Applications1 { get; set; }
    }
}
