//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationPortfolio.Domain.DataConnections
{
    using System;
    using System.Collections.Generic;
    
    public partial class document
    {
        public System.Guid object_id { get; set; }
        public long document_id { get; set; }
        public long document_type_id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<bool> is_image { get; set; }
        public string file_location { get; set; }
    
        public virtual baseobject baseobject { get; set; }
        public virtual document_type document_type { get; set; }
    }
}
