//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationPortfolio.Domain.DataConnections
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public Document()
        {
            this.ApplicationDocuments = new HashSet<ApplicationDocument>();
        }
    
        public System.Guid DocumentId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> DocumentTypeId { get; set; }
    
        public virtual ICollection<ApplicationDocument> ApplicationDocuments { get; set; }
        public virtual DocumentType DocumentType { get; set; }
    }
}
