//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationPortfolio.Domain.DataConnections
{
    using System;
    using System.Collections.Generic;
    
    public partial class framework
    {
        public long framework_id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<System.Guid> website_id { get; set; }
        public Nullable<System.Guid> application_id { get; set; }
    }
}
