//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationPortfolio.Domain.DataConnections
{
    using System;
    using System.Collections.Generic;
    
    public partial class notification_groups_contacts
    {
        public long notification_groups_contacts_id { get; set; }
        public Nullable<long> notification_group_id { get; set; }
        public Nullable<long> contact_id { get; set; }
    
        public virtual contact contact { get; set; }
        public virtual notification_groups notification_groups { get; set; }
    }
}
