//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationPortfolio.Domain.DataConnections
{
    using System;
    using System.Collections.Generic;
    
    public partial class notification
    {
        public long notifications_id { get; set; }
        public long contact_id { get; set; }
        public System.Guid object_id { get; set; }
        public bool and_dependants { get; set; }
        public bool and_ascendants { get; set; }
    
        public virtual baseobject baseobject { get; set; }
        public virtual contact contact { get; set; }
    }
}
