//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationPortfolio.Domain.DataConnections
{
    using System;
    using System.Collections.Generic;
    
    public partial class notification_groups_objects
    {
        public long notifications_groups_objects_id { get; set; }
        public long notification_group_id { get; set; }
        public Nullable<System.Guid> object_id { get; set; }
        public Nullable<long> object_type_id { get; set; }
    
        public virtual baseobject baseobject { get; set; }
        public virtual notification_groups notification_groups { get; set; }
        public virtual object_types object_types { get; set; }
    }
}
