//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationPortfolio.Domain.DataConnections
{
    using System;
    using System.Collections.Generic;
    
    public partial class object_types
    {
        public object_types()
        {
            this.baseobjects = new HashSet<baseobject>();
            this.notification_groups_objects = new HashSet<notification_groups_objects>();
        }
    
        public long object_type_id { get; set; }
        public string name { get; set; }
        public string details_table { get; set; }
    
        public virtual ICollection<baseobject> baseobjects { get; set; }
        public virtual ICollection<notification_groups_objects> notification_groups_objects { get; set; }
    }
}
