//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationPortfolio.Domain.DataConnections
{
    using System;
    using System.Collections.Generic;
    
    public partial class operating_systems
    {
        public operating_systems()
        {
            this.servers = new HashSet<server>();
        }
    
        public long operating_system_id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<server> servers { get; set; }
    }
}
