//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationPortfolio.Domain.DataConnections
{
    using System;
    using System.Collections.Generic;
    
    public partial class server_locations
    {
        public long location_id { get; set; }
        public string display_name { get; set; }
        public string short_name { get; set; }
        public Nullable<long> building_id { get; set; }
    
        public virtual building building { get; set; }
    }
}
