//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationPortfolio.Domain.DataConnections
{
    using System;
    using System.Collections.Generic;
    
    public partial class service_area
    {
        public service_area()
        {
            this.applications = new HashSet<application>();
        }
    
        public long service_area_id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<application> applications { get; set; }
    }
}
