//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationPortfolio.Domain.DataConnections
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServerChangeRequest
    {
        public int ServerChangeRequestId { get; set; }
        public System.Guid ServerId { get; set; }
        public string Description { get; set; }
        public System.DateTime ChangeDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string BackoutStrategy { get; set; }
    
        public virtual Server Server { get; set; }
    }
}
