//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationPortfolio.Domain.DataConnections
{
    using System;
    using System.Collections.Generic;
    
    public partial class webservice
    {
        public System.Guid webservice_id { get; set; }
        public bool is_websitebased { get; set; }
        public Nullable<System.Guid> website_id { get; set; }
        public Nullable<System.Guid> server_id { get; set; }
        public string url { get; set; }
        public Nullable<long> access_type_id { get; set; }
    
        public virtual access_types access_types { get; set; }
        public virtual server server { get; set; }
        public virtual website website { get; set; }
    }
}
