//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationPortfolio.Domain.DataConnections
{
    using System;
    using System.Collections.Generic;
    
    public partial class website
    {
        public website()
        {
            this.webservices = new HashSet<webservice>();
        }
    
        public System.Guid website_id { get; set; }
        public System.Guid webserver_id { get; set; }
    
        public virtual webserver webserver { get; set; }
        public virtual ICollection<webservice> webservices { get; set; }
    }
}
